### ISSUE TITLE
advanceCommitIndex中获取matchIndex的疑问

### ISSUE THREAD

**Issue by linglong1987** [wenweihu86/raft-java#12]
您好！ 在阅读您的代码时遇到一个问题，在RaftNode.java中的advanceCommitIndex()函数里面有一段code snippet：
        Arrays.sort(matchIndexes);
        long newCommitIndex = matchIndexes[peerNum / 2];

如果peerNum是6的话，那这样获取到的newCommitIndex 会不会并没有获得过半支持呢？ 个人感觉是不是应该将Arrays.sort修改为降序排序呢？

一点小疑问 如果能够得到您的解答 将十分感激！

**Comment by wenweihu86** [comment]
实际部署时，peerNum应该为基数的，不然就没法判定『大多数』。
即使这里peerNum是6的话，newCommitIndex = matchIndexes[3]，正好是一半支持（3、4、5）

**Comment by linglong1987** [comment]
十分感谢您的回答！
