### ISSUE TITLE
关于RaftConsensusService和RaftConsensusServiceAsync

### ISSUE THREAD

**Issue by winflex** [wenweihu86/raft-java#15]
为什么preVote和vote是拿异步代理，而appendEntries和installSnapshot是拿的是同步代理？都用异步的代理会有什么问题吗

**Comment by wenweihu86** [comment]
@winflex 因为appendEntries和installSnapshot是在新线程里执行的，所以即使同步，也是并行的。不过这里确实可以优化成异步，能提高并发。

**Comment by winflex** [comment]
@wenweihu86 是的
