### ISSUE TITLE
Class path contains multiple SLF4J bindings.

### ISSUE THREAD

**Issue by MrKingHH** [wenweihu86/raft-java#17]
Our project is using logback，when we use  dependency `raft-java-core` in our project. It's will report this error. Should we exclude the specific log system when we package?

**Comment by MrKingHH** [comment]
@wenweihu86

**Comment by wenweihu86** [comment]
ok, I will fix it recently

**Comment by wenweihu86** [comment]
org.apache.logging.log4j:log4j-slf4j-impl:jar:2.8.1:compile
this dependency is imported by rpc-java.
I need to update rpc-java to brpc-java.

**Comment by MrKingHH** [comment]
![image](https://user-images.githubusercontent.com/22386359/62776734-04f23900-bade-11e9-8a88-a7cdbe9c2cad.png)
Yup. I had found the reason. And i added the `<exclusions>` tag in my project. But this solution is not friendly.
![image](https://user-images.githubusercontent.com/22386359/62776809-35d26e00-bade-11e9-91ea-45c06e40044a.png)

**Comment by wenweihu86** [comment]
@MrKingHH slf4j implementation has beed removed.

**Comment by MrKingHH** [comment]
Thanks!
