### ISSUE TITLE
commitIndex没有持久化，可能导致状态机数据丢失

### ISSUE THREAD

**Issue by kanven** [wenweihu86/raft-java#19]
在RaftNode启动时commitIndex默认值为0，在RaftNode构造函数中设置其值：
` commitIndex = Math.max(snapshot.getMetaData().getLastIncludedIndex(), commitIndex);`
在接下来的代码中，有对提交到状态机数据到弥补：
`for (long index = snapshot.getMetaData().getLastIncludedIndex() + 1;
             index <= commitIndex; index++) {
            RaftMessage.LogEntry entry = raftLog.getEntry(index);
            if (entry.getType() == RaftMessage.EntryType.ENTRY_TYPE_DATA) {
                stateMachine.apply(entry.getData().toByteArray());
            } else if (entry.getType() == RaftMessage.EntryType.ENTRY_TYPE_CONFIGURATION) {
                applyConfiguration(entry);
            }
        }`
可是commitIndex还是lastIncludedIndex，如果生成快照之后，有数据提交到状态机，服务重启是否存在丢失数据到情况。

**Comment by wenweihu86** [comment]
@kanven 这里好像确实有问题，应该把commitIndex存在raftLog的meta里。近期修复，或者你也可以帮修复下。

**Comment by kanven** [comment]
@wenweihu86 commitIndex如果每次都提交对性能存在一定的影响， 我分析觉得在第一次心跳的时候会将commitIndex 弥补回来。如果在第一个心跳期间，客户端发起查询操作，状态机中可能不存在已提交数据。因此是否应该在这个过程中引入一个过渡状态，防止第一次心跳期间的查询。在第一次心跳完成后，服务才算真正启动完成。

**Comment by wenweihu86** [comment]
@kanven commitIndex如果不保存，leader也会丢失snapshot之后的数据把，靠心跳是弥补不回来的把

**Comment by kanven** [comment]
@wenweihu86 leader 有一个空转，从节点会返回他们的最厚日志条目索引号，这样leader有一次提交commitIndex的机会，这里应该可以弥补吧

**Comment by wenweihu86** [comment]
@kanven 嗯，可以在大多数节点都接受到后，此时leader更新自己的commitIndex，然后下次心跳，follower更新自己的commitIndex。

**Comment by wenweihu86** [comment]
fixed by this commit:
https://github.com/wenweihu86/raft-java/commit/128a1592605dd19e7373f6aa1194916d76d42666
