### ISSUE TITLE
启动的参数有点别扭

### ISSUE THREAD

**Issue by alohaking** [wenweihu86/raft-java#2]
一开始就指定所有peers，但是这些peer其实还未启动成功，能否以下面方式启动

```
server -s=localhost:8080
server -s=localhost:8081 -peer=localhost:8080
server -s=localhost:8082 -peer=localhost:8081
```

RaftNode中的peersMap动态产生而不是一开始就指定好。

另外发现启动3个节点成功后，kill掉leader，剩余2个节点1个成为leader，另一个一直请求被kill掉的节点地址，这样是否合理？

**Comment by wenweihu86** [comment]
1、如果不一开始指定所有peers的话，就不知道集群一共有多少个节点，这样就没法选主了。
2、”另一个一直请求被kill掉的节点地址“，请问这句是啥意思哈？
