### ISSUE TITLE
SegmentLog truncateSuffix（）有点问题

### ISSUE THREAD

**Issue by William-d-zk** [wenweihu86/raft-java#28]
![image](https://user-images.githubusercontent.com/8856002/73682625-acea6700-46fb-11ea-9696-dea5bd6245cb.png)

**Comment by wenweihu86** [comment]
@William-d-zk 多谢发现。如果方便的话，麻烦帮提个pr。

**Comment by wenweihu86** [comment]
fixed by the commit:
https://github.com/wenweihu86/raft-java/commit/b405f54420ab1b21b748ac3344482ff0c7a956ba
