### ISSUE TITLE
vote reponse处理不符合raft规则

### ISSUE THREAD

**Issue by yuhongye** [wenweihu86/raft-java#3]
`RaftNode`的第170~185行：
```
 if (currentTerm != response.getTerm() || state != NodeState.STATE_CANDIDATE) {
     LOG.info("ignore requestVote RPC result");
     return;
}

if (response.getTerm() > currentTerm) {
    // 不可能走到这儿
    ......
    stepDown(response.getTerm());
} else  {
...... 
} 

```

在raft论文中有一条规则：rpc request或response中包含的term T > currentTerm时，set currentTerm = T; set state = Follower。

上面代码第一个条件`if (currentTerm != response.term())`直接返回了，违反了这条规则。不相等就返回了，那也不可能走到那个大于的分支了。

**Comment by wenweihu86** [comment]
这里写错了，应该是
 if (currentTerm != request.getTerm() || state != NodeState.STATE_CANDIDATE) {
     LOG.info("ignore requestVote RPC result");
     return;
}

多谢指正！
方便的话，提个pr吧，我合并进去。
谢谢！

**Comment by yuhongye** [comment]
pr我就不提了，还在学习阶段，没有完全理解raft呢。

**Comment by wenweihu86** [comment]
那我fix下。

**Comment by wenweihu86** [comment]
已修复。
