### ISSUE TITLE
一个非常好的学习raft实现的项目，大赞

### ISSUE THREAD

**Issue by pyloque** [wenweihu86/raft-java#4]
最近一直在看老兄的代码，发现还有两点需要改进

1. prevote还没有实现
2. leader当选后第一步是追加一个no-op，我好像没看到

**Comment by wenweihu86** [comment]
1、prevote在其他raft实现中看到过，但是没太明白有什么作用，所以就没去实现。最近我再详细调研下，然后补充上去。
2、为啥要先追加一个no-op？不是心跳就可以了吗？
欢迎参与进来一起改进代码，谢谢！

**Comment by pyloque** [comment]
我还在仔细阅读论文，好复杂
有兴趣看我的知乎专栏，我把关于Raft理解到的都写在里面了 https://zhuanlan.zhihu.com/codehole

**Comment by wenweihu86** [comment]
@pyloque 知乎专栏写的很清晰，赞~
prevote功能已经加上了，有空可以帮review下代码。
目前代码有点冗余，后续完善。
