### ISSUE TITLE
protobuf生成java代码问题

### ISSUE THREAD

**Issue by day210** [wenweihu86/raft-java#46]
我想在几个request里增加字段，不清楚raft.proto生成RaftProto.java所用到的转换工具版本，我用最新版的[protobuf](https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.1)生成的代码很多地方有问题

**Comment by DaYu525** [comment]
添加相关依赖
`<dependency>`
            `<groupId>com.google.protobuf</groupId>`
            `<artifactId>protobuf-java</artifactId>`
            `<version>3.19.1</version>`
        `</dependency>`

**Comment by day210** [comment]
添加相关依赖解决了
`<dependency>`
            `<groupId>com.google.protobuf</groupId>`
            `<artifactId>protobuf-java</artifactId>`
            `<version>3.19.1</version>`
        `</dependency>`
