### ISSUE TITLE
部署文件deploy.sh错误

### ISSUE THREAD

**Issue by wangwg1** [wenweihu86/raft-java#6]
mkdir client
cd client
cp -f ../../target/$EXAMPLE_ZIP .
tar -zxvf $EXAMPLE_ZIP
chmod +x ./bin/*.sh

应改为

mkdir client
cd client
cp -f ../../target/$EXAMPLE_TAR .
tar -zxvf $EXAMPLE_TAR
chmod +x ./bin/*.sh

**Comment by wenweihu86** [comment]
多谢指正问题，已修复！
