### ISSUE TITLE
window下用mingw运行，会报找不到main class的错误。

### ISSUE THREAD

**Issue by wangwg1** [wenweihu86/raft-java#7]
将JAVA_CP改为
JAVA_CP=" -cp conf;lib/* "
原因是windows下分隔符为 分号“；”
您是否考虑建一个run_*.bat，或者在脚本中做一个操作系统判断
用uname -a 判断一下可以，分别是大写的CYGWIN开头和MINGW开头。
我的系统显示的是：
CYGWIN_NT-6.1 ********************* 2.10.0(0.325/5/3) 2018-02-02 15:16 x86_64 Cygwin
MINGW64_NT-6.1 ********************* 2.9.0(0.318/5/3) 2017-10-05 15:05 x86_64 Msys

CYGWIN下run_server.sh最后一行有“语法错误: 未预期的文件结尾“；第二行有“$\r”错误。
把空行删掉“$\r”错误就好了；
将eclipse工程的文件格式改为unix了。properties-->new text file line delimiter-->unix；新建一个文件，把内容复制过去，“未预期的文件结尾”的错误就没有了。
这两个就都能运行了。我是单独测的run_server.sh。没有重新将deploy.sh运行部署。

**Comment by wenweihu86** [comment]
我没有windows的环境，所有就没写windows相关的部署脚本；你如果方便的话，可否提交pull request？

**Comment by wangwg1** [comment]
可以的。

2018-07-24 

music_cn 



发件人：Wenwei Hu <notifications@github.com>
发送时间：2018-07-22 09:44
主题：Re: [wenweihu86/raft-java] window下用mingw运行，会报找不到main class的错误。 (#7)
收件人："wenweihu86/raft-java"<raft-java@noreply.github.com>
抄送："wangwg1"<music_cn@163.com>,"Author"<author@noreply.github.com>

我没有windows的环境，所有就没写windows相关的部署脚本；你如果方便的话，可否提交pull request？

**Comment by wenweihu86** [comment]
已merge到master。
多谢pull request！
